---

- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: 'Install packages'
    package:
      name:
        - htop
        - vim
        - tmux
        - keepassxc
        - curl

  - name: 'Copy .vimrc'
    copy:
      src: dot_files/.vimrc
      dest: /home/pshnn/.vimrc
      owner: pshnn
      group: pshnn

  - name: 'Copy .tmux.conf'
    copy:
      src: dot_files/.tmux.conf
      dest: /home/pshnn/.tmux.conf
      owner: pshnn
      group: pshnn

  - name: 'Copy .bashrc'
    copy:
      src: dot_files/.bashrc
      dest: /home/pshnn/.bashrc
      owner: pshnn
      group: pshnn

  - name: 'Create Vim autoload directory'
    file:
      path: /home/pshnn/.vim/autoload
      state: directory
      owner: pshnn
      group: pshnn

  - name: 'Download vim-plug'
    get_url:
      url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      dest: /home/pshnn/.vim/autoload/plug.vim
      owner: pshnn
      group: pshnn

  - name: 'Install nvm'
    shell: >
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh |
      bash
    args:
      creates: /home/pshnn/.nvm/nvm.sh
