---

- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: 'Install packages'
    package:
      name:
        - htop
        - vim
        - tmux

  - name: 'Copy .vimrc'
    copy:
      src: dot_files/.vimrc
      path: /home/pshnn/.vimrc
      owner: pshnn
      group: pshnn
